name: CI/CD Pipeline with Python Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with: 
        python-version: "3.x"
        cache: "pip"
    - name: Install Dependecies
      run: |
          make install
    - name: Format Code with black
      run: |
        make format
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test code assertions
      run: |
        make test
    - name: Build Docker Container Image
      run: |
        make build
